export const ErrorCodes = {
    "auth/invalid-email": "Invalid email format.",
    "auth/user-disabled": "User account is disabled.",
    "auth/user-not-found": "User not found.",
    "auth/wrong-password": "Incorrect login credentials.",
    "auth/email-already-in-use": "Email is already in use.",
    "auth/weak-password": "Password is too weak.",
    "auth/operation-not-allowed": "Operation not allowed.",
    "auth/requires-recent-login": "Please log in again.",
    "auth/account-exists-with-different-credential": "Email is associated with another account.",
    "auth/too-many-requests": "Too many requests. Try again later.",
    "auth/network-request-failed": "Network error.",
    "auth/credential-already-in-use": "Credential is already linked to another account.",
    "auth/invalid-verification-code": "Invalid verification code.",
    "auth/invalid-verification-id": "Invalid verification ID.",
    "auth/invalid-credential": "Incorrect login credentials.",
    "auth/unauthorized-domain": "Unauthorized domain.",
    "auth/internal-error": "An error occurred.",
    "auth/popup-blocked": "Popup was blocked.",
    "auth/popup-closed-by-user": "Popup closed by user.",
    "auth/web-storage-unsupported": "Web storage is unsupported.",
    "auth/invalid-api-key": "Invalid API key.",
    "auth/app-not-authorized": "App is not authorized.",
    "auth/app-deleted": "App has been deleted."
};
